# Generated by Django 4.0.4 on 2022-05-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_created_at_orderproduct_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
